# Generated by Django 5.0.4 on 2024-06-29 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impromptu_api', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
