# Generated by Django 5.0.4 on 2024-06-29 14:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impromptu_api', '0005_post_additional_info_post_email_post_name_post_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
