# Generated by Django 5.0.4 on 2024-06-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impromptu_api', '0006_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
